# Generated by Django 6.0.3 on 2026-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
